const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const bankDir=path.join(__dirname,'..','banks');
for(const name of fs.readdirSync(bankDir).filter(name=>name.endsWith('.js')).sort())require(path.join(bankDir,name));
const {Game,plan,modes,answerKey}=require('../engine.js');
const D=require('../questions.js');

const config=(mode='classic',count=1)=>({auto:false,categories:D.categories,capacity:100,rounds:[{mode,count,category:'Mixed'}]});
function advanceToQuestion(g,now){let guard=0;while(g.phase!=='question'&&guard++<30){if(g.phase==='roundIntro'){g.host(g.hostToken,{action:'startRound'},now+1);now+=1}else if(g.deadline){now=g.deadline;g.tick(now)}else throw new Error('Game stalled in '+g.phase)}assert.equal(g.phase,'question');return now}
function game(mode,count=1,n=2){let g=new Game(config(mode,count),'ABCDEF',1000),p=Array.from({length:n},(_,i)=>g.join({name:'Player '+i},1000)),now=1000;g.start(now);now=advanceToQuestion(g,now);return{g,p,now}}
const key=q=>answerKey(q.answer),wrongKey=q=>q.options.map(answerKey).find(x=>x!==key(q))||'Z';

test('all 22 categories have large valid standard-question pools',()=>{
  assert.equal(D.categories.length,22);
  assert.ok(D.questions.length>20000);
  for(const c of D.categories)assert.ok(D.questions.filter(q=>q.category===c).length>=500,c+' should have at least 500 questions');
  for(const q of D.questions){
    assert.equal(q.options.length,4,q.id);
    assert.equal(new Set(q.options.map(String)).size,4,q.id);
    assert.ok(q.options.includes(q.answer),q.id);
  }
});

test('room admits exactly 100 players and rejects the 101st',()=>{let g=new Game(config());for(let i=0;i<100;i++)g.join({name:'P'+i},1000);assert.equal(g.players.length,100);assert.throws(()=>g.join({name:'P100'}),/full/)});
test('names and host permissions are enforced',()=>{let g=new Game(config());g.join({name:'Leon'});assert.throws(()=>g.join({name:'leon'}),/already/);assert.throws(()=>g.host('wrong',{action:'start'}),/private/)});
test('private state hides correctness and answer before reveal',()=>{let{g,p,now}=game(),q=g.q();g.answer(p[0].token,{value:key(q)},now+1);let s=g.state(p[0].token,now+1);assert.equal(s.q.answer,undefined);assert.equal(s.me.answer.correct,undefined);assert.equal(s.players[0].answer,undefined);g.reveal(now+2);assert.equal(g.state(p[0].token,now+2).q.answer,g.q().answer)});
test('answers cannot be changed; points are awarded once',()=>{let{g,p,now}=game(),q=g.q();g.answer(p[0].token,{value:key(q)},now+1);assert.throws(()=>g.answer(p[0].token,{value:key(q)},now+2),/locked/);g.answer(p[1].token,{value:wrongKey(q)},now+3);assert.equal(p[0].score,2);g.reveal(now+4);assert.equal(p[0].score,2)});
test('closest wins awards ties and exact answers earn 100',()=>{let{g,p}=game('closest',1,3),v=g.q().value;g.answer(p[0].token,{value:v-2},1100);g.answer(p[1].token,{value:v+2},1101);g.answer(p[2].token,{value:v+3},1102);assert.deepEqual(p.map(x=>x.score),[50,50,0]);let h=game('closest',1,2),v2=h.g.q().value;h.g.answer(h.p[0].token,{value:v2},1100);h.g.answer(h.p[1].token,{value:v2+1},1101);assert.deepEqual(h.p.map(x=>x.score),[100,0])});
test('steal round lets only the fastest correct player steal up to five',()=>{let{g,p,now}=game('steal',1,2),q=g.q();p[1].score=3;g.answer(p[0].token,{value:key(q)},now+1);g.answer(p[1].token,{value:wrongKey(q)},now+2);assert.ok(g.pendingSteal);g.steal(p[0].token,{target:p[1].id},now+3);assert.deepEqual(p.map(x=>x.score),[5,0]);assert.equal(p[0].steals,3)});
test('toxic round removes five points for a wrong answer',()=>{let{g,p,now}=game('toxic',1,3),q=g.q();p.forEach(x=>x.score=20);g.answer(p[0].token,{value:key(q)},now+1);g.answer(p[1].token,{value:wrongKey(q)},now+2);g.answer(p[2].token,{value:wrongKey(q)},now+3);assert.deepEqual(p.map(x=>x.score),[23,15,15])});
test('betting loses only the available stake',()=>{let{g,p,now}=game('bet'),q=g.q();p[0].score=50;g.answer(p[0].token,{value:wrongKey(q),stake:5000},now+1);g.reveal(now+2);assert.equal(p[0].score,0)});
test('chaos shield stops theft; last answerer gets a card window; power is single-use',()=>{let{g,p,now}=game('chaos',2),q=g.q();p[0].card='steal';p[1].card='shield';p[1].score=200;g.answer(p[0].token,{value:key(q)},now+1);g.power(p[0].token,{target:p[1].id},now+2);g.answer(p[1].token,{value:key(q)},now+3);assert.equal(g.phase,'question');g.power(p[1].token,{},now+4);assert.throws(()=>g.power(p[0].token,{target:p[1].id},now+5),/Answer the question|card/);g.tick(g.deadline);assert.deepEqual(p.map(x=>x.score),[2,201])});
test('higher lower is determined by the actual number',()=>{let{g,p}=game('higher');assert.equal(g.q().answer,g.q().value>g.q().reference?'Higher':'Lower');g.answer(p[0].token,{value:g.q().answer},1100);g.reveal(1200);assert.equal(p[0].score,2)});
test('final uses eight seconds and doubles the speed-ladder score',()=>{let{g,p,now}=game('final'),q=g.q();assert.equal(g.deadline,now+8000);g.answer(p[0].token,{value:key(q)},now+1);g.answer(p[1].token,{value:wrongKey(q)},now+2);assert.equal(p[0].score,4)});
test('pause freezes expiry and shifts deadlines on resume',()=>{let{g}=game();let end=g.deadline;g.host(g.hostToken,{action:'pause'},2000);g.tick(100000);assert.equal(g.phase,'question');g.host(g.hostToken,{action:'pause'},102000);assert.equal(g.deadline,end+100000);g.tick(g.deadline);assert.equal(g.phase,'reveal')});
test('Bingo schedules all nine cells so a full house is possible',()=>{let{g,p,now}=game('bingo',9,1);assert.equal(g.questions.length,9);assert.equal(new Set(p[0].grid).size,9);for(let i=0;i<9;i++){g.answer(p[0].token,{value:g.q().answer},now+1);if(i<8){g.host(g.hostToken,{action:'next'},now+2);now=advanceToQuestion(g,now+2)}}assert.equal(p[0].marks.length,9);assert.equal(p[0].lines.length,8);assert.equal(p[0].score,9+2400+1000)});
test('music locks first buzz, reopens on wrong title, accepts aliases and artist',()=>{let c=config('music');c.songs=[{answer:'Test Song',artist:'Test Artist',aliases:'The Test Song',category:'General Knowledge',audio:'data:audio/mpeg;base64,AAAA'}];let g=new Game(c,'ABCDEF',1000),a=g.join({name:'A'},1000),b=g.join({name:'B'},1000),now=1000;g.start(now);now=advanceToQuestion(g,now);g.buzzer(a.token,now+1);assert.throws(()=>g.buzzer(b.token,now+2),/first/);g.answer(a.token,{value:'Wrong'},now+3);g.buzzer(b.token,now+4);g.answer(b.token,{value:'The Test Song',artist:'Test Artist'},now+5);g.reveal(now+6);assert.equal(b.score,200)});
test('music buzz expires and becomes an attempt',()=>{let c=config('music');c.songs=[{answer:'Song',category:'General Knowledge',audio:'data:audio/mpeg;base64,AAAA'}];let g=new Game(c,'ABCDEF',1000),a=g.join({name:'A'},1000),now=1000;g.start(now);now=advanceToQuestion(g,now);g.buzzer(a.token,now+1);g.tick(now+12001);assert.equal(g.buzz,null);assert.ok(a.answer)});
test('custom planning prevents trivia repetition across classic and clue-backed modes',()=>{let out=plan({categories:['General Knowledge'],rounds:[{mode:'classic',count:5},{mode:'clue',count:5}]});assert.equal(new Set(out.map(q=>q.id)).size,10)});
test('clue-backed modes are playable from the main trivia pool',()=>{for(const mode of ['clue','whoami','connections']){let out=plan({categories:['General Knowledge'],rounds:[{mode,count:5,category:'General Knowledge'}]});assert.equal(out.length,5);assert.ok(out.every(q=>q.mode===mode&&q.options.length===4))}});
test('Head-to-Head selects two players, blocks spectators and scores 2 then 1',()=>{let{g,p}=game('headtohead',1,4),q=g.q(),duel=p.filter(x=>g.headToHeadIds.includes(x.id)),spectator=p.find(x=>!g.headToHeadIds.includes(x.id));assert.equal(duel.length,2);assert.throws(()=>g.answer(spectator.token,{value:g.answerKey?.(q.answer)||q.answer},1100));let key=require('../engine.js').answerKey(q.answer);g.answer(duel[0].token,{value:key},1101);g.answer(duel[1].token,{value:key},1102);assert.deepEqual(duel.map(x=>x.score),[2,1])});
test('Elimination knocks out exactly one worst active player per question',()=>{let{g,p}=game('elimination',1,4),q=g.q(),key=require('../engine.js').answerKey(q.answer),wrong=q.options.map(require('../engine.js').answerKey).find(x=>x!==key)||'Z';g.answer(p[0].token,{value:key},1100);g.answer(p[1].token,{value:wrong},1101);g.answer(p[2].token,{value:wrong},1102);g.answer(p[3].token,{value:wrong},1103);assert.equal(g.eliminatedIds.length,1);assert.equal(g.activePlayers().length,3)});
test('Chasedown marks the leader and awards correct chasers a +2 bonus',()=>{let{g,p}=game('chasedown',1,3);p[0].score=10;g.prepareQuestion(g.q());assert.equal(g.chasedownLeaderId,p[0].id);let key=require('../engine.js').answerKey(g.q().answer);g.answer(p[0].token,{value:key},1100);g.answer(p[1].token,{value:key},1101);g.answer(p[2].token,{value:key},1102);assert.deepEqual(p.map(x=>x.score),[13,4,3])});
test('picture and quote pools produce real questions with choices',()=>{for(let m of ['picture','quote']){let{g}=game(m);assert.equal(g.q().options.length,4);if(m==='picture')assert.ok(g.q().image.startsWith('data:image/'))}});
test('automatic quiz reaches finished; manual quiz waits at reveal',()=>{let{g}=game();g.tick(g.deadline);g.tick(g.deadline+10000);assert.equal(g.phase,'reveal');g.host(g.hostToken,{action:'auto',value:true},g.deadline+11000);g.tick(g.deadline+12000);assert.equal(g.phase,'finished')});
test('reconnection with existing player token restores personal state',()=>{let{g,p,now}=game(),q=g.q();let k=key(q);g.answer(p[0].token,{value:k},now+1);let s=g.state(p[0].token,now+2);assert.equal(s.me.id,p[0].id);assert.equal(s.me.answer.value,k);assert.equal(g.players.length,2)});
test('all 20 current modes are implemented',()=>{assert.equal(Object.keys(modes).length,20)});
test('every mode has a playable planner path',()=>{for(const mode of Object.keys(modes)){let c={categories:D.categories,rounds:[{mode,count:mode==='bingo'?9:1,category:'Mixed'}]};if(mode==='music')c.songs=[{answer:'Test Song',artist:'Test Artist',category:'General Knowledge',audio:'data:audio/mpeg;base64,AAAA'}];let out=plan(c);assert.ok(out.length>=1,mode)}});
test('random planning succeeds repeatedly and stays inside selected categories',()=>{for(let i=0;i<100;i++){let category=D.categories[i%D.categories.length],out=plan({play:'random',categories:[category],roundCount:5,perRound:3});assert.equal(new Set(out.map(q=>q.round)).size,5);assert.ok(out.every(q=>q.category===category))}});
test('dedicated buzzer round gives the fastest player the only attempt',()=>{let{g,p,now}=game('buzzer',1,2),q=g.q();g.buzzer(p[0].token,now+1);assert.throws(()=>g.buzzer(p[1].token,now+2),/first/);g.tick(now+5001);g.answer(p[0].token,{value:wrongKey(q)},now+5002);assert.equal(g.phase,'reveal');assert.equal(p[0].score,0);assert.throws(()=>g.buzzer(p[1].token,now+5003),/not open/)});
