(function(root){
const categories=['General Knowledge','Lord of the Rings','Game of Thrones','Disney','Video Games','Science','Harry Potter','Manchester United','Marvel','DC','Pokémon','Marine Biology','Cats','Animals','Films','TV Shows'];
const raw={
'General Knowledge':[
['What is the capital of Australia?','Canberra','Sydney','Melbourne','Perth'],['Which planet is closest to the Sun?','Mercury','Venus','Mars','Earth'],['What currency is used in Japan?','Yen','Won','Yuan','Rupee'],['Which country is home to the city of Marrakech?','Morocco','Egypt','Turkey','Tunisia'],['How many sides does a hexagon have?','Six','Five','Seven','Eight'],['Which ocean is the largest?','Pacific','Atlantic','Indian','Arctic'],['Who painted the Mona Lisa?','Leonardo da Vinci','Michelangelo','Vincent van Gogh','Pablo Picasso'],['Which language is primarily spoken in Brazil?','Portuguese','Spanish','French','Italian'],['What is the smallest prime number?','2','0','1','3'],['Which instrument has keys, pedals and strings?','Piano','Trumpet','Clarinet','Flute']],
'Lord of the Rings':[
['Who carries the One Ring to Mount Doom?','Frodo Baggins','Bilbo Baggins','Merry Brandybuck','Peregrin Took'],['What is the name of Frodo’s loyal companion?','Samwise Gamgee','Gimli','Boromir','Éomer'],['Who forged the One Ring?','Sauron','Saruman','Gandalf','Elrond'],['What is the name of the inn in Bree?','The Prancing Pony','The Green Dragon','The Golden Perch','The Ivy Bush'],['Which creature does Gandalf confront in Moria?','A Balrog','A dragon','A troll king','A giant spider'],['What is Aragorn’s reforged sword called?','Andúril','Sting','Glamdring','Orcrist'],['Who is the ruler of Rohan when the Fellowship arrives?','Théoden','Denethor','Elrond','Thranduil'],['What was Gollum’s original name?','Sméagol','Déagol','Gríma','Radagast'],['Which member of the Fellowship is an elf?','Legolas','Gimli','Boromir','Aragorn'],['Where is the One Ring destroyed?','Mount Doom','Isengard','Helm’s Deep','Minas Tirith']],
'Game of Thrones':[
['What is House Stark’s ancestral seat?','Winterfell','Riverrun','Highgarden','Casterly Rock'],['What is House Lannister’s ancestral seat?','Casterly Rock','Winterfell','Dragonstone','The Eyrie'],['Which family uses a three-headed dragon as its sigil?','Targaryen','Stark','Baratheon','Tyrell'],['Who is Arya Stark’s older sister?','Sansa','Brienne','Lyanna','Catelyn'],['What is Arya’s sword called?','Needle','Ice','Longclaw','Oathkeeper'],['Which organisation guards the Wall?','The Night’s Watch','The Kingsguard','The Golden Company','The Unsullied'],['Who is known as the Onion Knight?','Davos Seaworth','Jorah Mormont','Bronn','Barristan Selmy'],['Which city is home to the Iron Bank?','Braavos','Pentos','Meereen','Volantis'],['Who is Daenerys’s largest dragon?','Drogon','Rhaegal','Viserion','Balerion'],['Which house has a rose as its sigil?','Tyrell','Martell','Greyjoy','Tully']],
'Disney':[
['What is Simba’s father called?','Mufasa','Scar','Rafiki','Zazu'],['What kind of animal is Dumbo?','Elephant','Hippo','Rhino','Giraffe'],['Which princess has a chameleon called Pascal?','Rapunzel','Ariel','Belle','Jasmine'],['What is the name of the snowman in Frozen?','Olaf','Sven','Kristoff','Hans'],['Which Disney film features the city of Agrabah?','Aladdin','Mulan','Hercules','Tangled'],['What is Ariel’s crab friend called?','Sebastian','Flounder','Scuttle','Eric'],['Who is the villain in The Little Mermaid?','Ursula','Maleficent','Cruella','Mother Gothel'],['What does Cinderella’s carriage begin as?','A pumpkin','A watermelon','A potato','An apple'],['Which character is a wooden puppet?','Pinocchio','Peter Pan','Jiminy Cricket','Geppetto'],['What is the name of Moana’s demigod companion?','Maui','Heihei','Pua','Tamatoa']],
'Video Games':[
['What is Mario’s brother called?','Luigi','Wario','Yoshi','Toad'],['Who is the usual playable hero of The Legend of Zelda?','Link','Zelda','Ganondorf','Impa'],['Which Minecraft enemy explodes near players?','Creeper','Enderman','Skeleton','Zombie'],['Which company created Sonic the Hedgehog?','Sega','Nintendo','Capcom','Sony'],['What is the name of Halo’s armoured protagonist?','Master Chief','Marcus Fenix','Gordon Freeman','Solid Snake'],['In Portal, what is the AI antagonist called?','GLaDOS','Cortana','SHODAN','Wheatley'],['Which series features the city of Rapture?','BioShock','Fallout','Half-Life','Mass Effect'],['Which Nintendo series features Isabelle and Tom Nook?','Animal Crossing','Splatoon','Pikmin','Fire Emblem'],['Which game features blocks called tetrominoes?','Tetris','Pac-Man','Pong','Space Invaders'],['Which series features the character Solid Snake?','Metal Gear','Splinter Cell','Hitman','Deus Ex']],
'Science':[
['What is the chemical symbol for gold?','Au','Ag','Fe','Gd'],['What gas do plants take in during photosynthesis?','Carbon dioxide','Oxygen','Helium','Hydrogen'],['Which part of a cell contains most of its DNA in humans?','Nucleus','Ribosome','Cell membrane','Cytoplasm'],['What is the SI unit of force?','Newton','Watt','Joule','Pascal'],['What is the chemical formula for water?','H₂O','CO₂','O₂','NaCl'],['What charge does an electron carry?','Negative','Positive','Neutral','It varies between atoms'],['Which organ pumps blood around the human body?','Heart','Liver','Kidney','Lung'],['What is the closest star to Earth?','The Sun','Sirius','Proxima Centauri','Polaris'],['What process turns a liquid into a gas at its surface?','Evaporation','Condensation','Freezing','Melting'],['Which scientist proposed general relativity?','Albert Einstein','Isaac Newton','Marie Curie','Charles Darwin']],
'Harry Potter':[
['Which Hogwarts house is Harry sorted into?','Gryffindor','Slytherin','Ravenclaw','Hufflepuff'],['What is Hermione’s surname?','Granger','Weasley','Lovegood','Longbottom'],['What is Harry’s owl called?','Hedwig','Errol','Pigwidgeon','Fawkes'],['Which platform does the Hogwarts Express depart from?','9¾','7½','10¼','8¾'],['Which position does Harry play in Quidditch?','Seeker','Keeper','Beater','Chaser'],['What is the spell commonly used to disarm?','Expelliarmus','Lumos','Accio','Alohomora'],['Who is the Hogwarts groundskeeper in Harry’s first year?','Rubeus Hagrid','Argus Filch','Albus Dumbledore','Severus Snape'],['Which creature is Aragog?','Acromantula','Basilisk','Hippogriff','Thestral'],['What is Voldemort’s birth name?','Tom Marvolo Riddle','Tobias Snape','Lucius Malfoy','Gellert Grindelwald'],['What shape is Harry’s Patronus?','Stag','Otter','Doe','Hare']],
'Manchester United':[
['What is Manchester United’s home stadium?','Old Trafford','Anfield','Goodison Park','St James’ Park'],['What is the club’s familiar nickname?','The Red Devils','The Toffees','The Magpies','The Gunners'],['Who managed United during the 1999 treble?','Alex Ferguson','Matt Busby','José Mourinho','David Moyes'],['Who scored United’s winning goal in the 1999 Champions League final?','Ole Gunnar Solskjær','Teddy Sheringham','David Beckham','Andy Cole'],['Which club did United beat in the 1999 Champions League final?','Bayern Munich','Barcelona','Juventus','Real Madrid'],['What was Manchester United originally called?','Newton Heath','Manchester Central','Salford Athletic','Lancashire United'],['Who captained United in the 2008 Champions League final?','Rio Ferdinand','Gary Neville','Ryan Giggs','Paul Scholes'],['Which goalkeeper saved Nicolas Anelka’s penalty in that final?','Edwin van der Sar','Peter Schmeichel','David de Gea','Fabien Barthez'],['Which United legend was nicknamed the King and wore number 7?','Eric Cantona','Roy Keane','Denis Irwin','Nicky Butt'],['Which manager led United to the 1968 European Cup?','Matt Busby','Alex Ferguson','Tommy Docherty','Ron Atkinson']],
'Marvel':[
['What is Iron Man’s real name?','Tony Stark','Bruce Banner','Steve Rogers','Clint Barton'],['What is Thor’s hammer called?','Mjolnir','Stormbreaker','Gungnir','Hofund'],['What fictional nation is Black Panther associated with?','Wakanda','Latveria','Genosha','Sokovia'],['What is Spider-Man Peter Parker’s aunt called?','May','June','Mary','Anna'],['Who transforms into the Hulk?','Bruce Banner','Tony Stark','Scott Lang','Stephen Strange'],['Which hero uses a shield made with vibranium?','Captain America','Hawkeye','Ant-Man','Star-Lord'],['What is Doctor Strange’s first name?','Stephen','Steven','Samuel','Simon'],['Which Guardian is a tree-like alien?','Groot','Rocket','Drax','Nebula'],['What is the name of Loki’s adoptive father?','Odin','Thanos','Ego','Heimdall'],['Which hero is also called the Scarlet Witch?','Wanda Maximoff','Natasha Romanoff','Carol Danvers','Jean Grey']],
'DC':[
['What is Batman’s real name?','Bruce Wayne','Clark Kent','Barry Allen','Hal Jordan'],['Which city is Superman most associated with?','Metropolis','Gotham','Central City','Star City'],['What is Wonder Woman’s given name?','Diana','Selina','Kara','Barbara'],['Which villain is also known as the Clown Prince of Crime?','The Joker','The Riddler','The Penguin','Two-Face'],['What is Superman’s birth name?','Kal-El','Jor-El','Zod','Kon-El'],['Which hero is king of Atlantis?','Aquaman','Green Arrow','Cyborg','Shazam'],['Which hero is associated with a power ring?','Green Lantern','Batman','The Flash','Superman'],['What is Batman’s butler called?','Alfred Pennyworth','Lucius Fox','James Gordon','Harvey Bullock'],['Which material famously weakens Superman?','Kryptonite','Vibranium','Adamantium','Promethium'],['Which DC hero is an archer?','Green Arrow','Green Lantern','Blue Beetle','Red Tornado']],
'Pokémon':[
['Which type is Pikachu?','Electric','Fire','Water','Normal'],['What does Charmander evolve into first?','Charmeleon','Charizard','Dragonair','Magmar'],['Which Pokémon is number 001 in the National Pokédex?','Bulbasaur','Pikachu','Charmander','Squirtle'],['What item is typically used to catch a Pokémon?','Poké Ball','Rare Candy','Potion','Repel'],['Which type is super effective against Water?','Electric','Fire','Ice','Steel'],['Which Pokémon travels with Jessie and James in the original anime?','Meowth','Ditto','Jigglypuff','Psyduck'],['Which region is featured in Pokémon Red and Blue?','Kanto','Johto','Hoenn','Sinnoh'],['What does Magikarp evolve into?','Gyarados','Milotic','Dragonite','Lapras'],['Which Pokémon can evolve into Vaporeon?','Eevee','Pikachu','Vulpix','Poliwag'],['Which Pokémon is famously associated with sleeping and blocking paths?','Snorlax','Abra','Slowpoke','Slaking']],
'Marine Biology':[
['How many arms does an octopus typically have?','Eight','Six','Ten','Twelve'],['Which is the largest living animal?','Blue whale','Whale shark','Giant squid','Orca'],['What kind of animal is a dolphin?','Mammal','Fish','Reptile','Amphibian'],['What are coral animals called?','Polyps','Spores','Larvae only','Nodules'],['What do sharks have skeletons mainly made of?','Cartilage','Bone','Chitin','Silica'],['Which marine animal has males that carry developing young in a brood pouch?','Seahorse','Sea turtle','Octopus','Clownfish'],['Which fish is famous for symbiosis with sea anemones?','Clownfish','Swordfish','Tuna','Mackerel'],['Which animal is an echinoderm?','Sea star','Jellyfish','Lobster','Clam'],['What do baleen whales use to filter food?','Baleen plates','Rows of sharp teeth','Gills','Tentacles'],['Which marine animal is a cephalopod?','Cuttlefish','Sea cucumber','Sea urchin','Sea horse']],
'Cats':[
['What is a young cat called?','Kitten','Cub','Pup','Foal'],['What is the usual term for a male breeding cat?','Tom','Buck','Boar','Ram'],['Which cat breed is famous for often having no coat?','Sphynx','Maine Coon','Persian','Ragdoll'],['What is a cat’s scientific species name?','Felis catus','Canis lupus','Panthera leo','Lynx lynx'],['What is the technical name for whiskers?','Vibrissae','Papillae','Cilia','Follicles'],['What does crepuscular mean?','Most active around dawn and dusk','Only active at midday','Unable to see in dim light','Sleeping all winter'],['What is the striped coat pattern commonly called?','Tabby','Tuxedo','Pointed','Calico'],['Which sense uses a cat’s vomeronasal organ?','Chemical scent detection','Hearing','Vision','Balance'],['Which big cat generally cannot retract its claws fully?','Cheetah','Tiger','Leopard','Jaguar'],['Which cat breed takes its name from an American state?','Maine Coon','Siamese','Bengal','Persian']],
'Animals':[
['Which mammal lays eggs?','Platypus','Otter','Badger','Hedgehog'],['What is a group of lions commonly called?','Pride','School','Pod','Colony'],['Which bird is the largest living bird?','Ostrich','Emu','Cassowary','Albatross'],['How many legs does an insect have?','Six','Eight','Ten','Four'],['Which animal is a marsupial?','Kangaroo','Rabbit','Fox','Squirrel'],['What is a baby frog commonly called?','Tadpole','Nymph','Larva beetle','Chick'],['What is the tallest living land animal?','Giraffe','Elephant','Ostrich','Camel'],['Which animal is a primate?','Lemur','Meerkat','Koala','Sloth'],['Which animal builds dams?','Beaver','Otter','Muskrat','Badger'],['What is a female deer commonly called?','Doe','Ewe','Mare','Sow']],
'Films':[
['Who directed Jurassic Park (1993)?','Steven Spielberg','James Cameron','George Lucas','Ridley Scott'],['Which film features a shark terrorising Amity Island?','Jaws','Deep Blue Sea','The Meg','Shark Tale'],['What is the name of the cowboy toy in Toy Story?','Woody','Buzz','Andy','Rex'],['Which film franchise features the character Jack Sparrow?','Pirates of the Caribbean','Indiana Jones','The Mummy','National Treasure'],['Who plays Neo in The Matrix (1999)?','Keanu Reeves','Brad Pitt','Tom Cruise','Nicolas Cage'],['What is the name of the kingdom in Shrek?','Duloc','Arendelle','Agrabah','Narnia'],['Which film features the DeLorean time machine?','Back to the Future','The Terminator','Ghostbusters','Blade Runner'],['Which film features the character Ellen Ripley?','Alien','Predator','The Thing','Dune'],['Who directed Titanic (1997)?','James Cameron','Steven Spielberg','Peter Jackson','Christopher Nolan'],['Which film follows a robot called WALL-E?','WALL-E','Robots','Big Hero 6','The Iron Giant']],
'TV Shows':[
['What is the coffee shop in Friends called?','Central Perk','Monk’s Café','The Peach Pit','Café Nervosa'],['Which show features Walter White?','Breaking Bad','The Wire','Dexter','Ozark'],['What is the surname of the family in The Simpsons?','Simpson','Griffin','Belcher','Smith'],['Which sci-fi show features the TARDIS?','Doctor Who','Star Trek','Stargate SG-1','Red Dwarf'],['Which sitcom features Del Boy and Rodney?','Only Fools and Horses','Porridge','Blackadder','The Young Ones'],['Which show is set largely in Hawkins, Indiana?','Stranger Things','Dark','Lost','The X-Files'],['What is the name of the pub in EastEnders?','The Queen Victoria','The Rovers Return','The Woolpack','The Dog in the Pond'],['Which show features the paper company Dunder Mifflin?','The Office (US)','Parks and Recreation','Community','30 Rock'],['Which TV detective is associated with 221B Baker Street?','Sherlock Holmes','Hercule Poirot','Columbo','Inspector Morse'],['Which animated show features the town of South Park?','South Park','Family Guy','Futurama','American Dad!']]
};
const questions=categories.flatMap((category,c)=>raw[category].map((r,i)=>({id:`c${c}q${i}`,category,prompt:r[0],answer:r[1],options:r.slice(1)})));
const numeric=[
['How many bones are in a typical adult human skeleton?',206,'bones','Science'],['How many elements have atomic numbers from 1 to 118?',118,'elements','Science'],['In which year was the first Harry Potter novel published in the UK?',1997,'year','Harry Potter'],['How many players are on one Quidditch team on the pitch?',7,'players','Harry Potter'],['In which year did Manchester United win their 1999 treble?',1999,'year','Manchester United'],['In which year was Manchester United founded as Newton Heath?',1878,'year','Manchester United'],['How many Pokémon were in the original Generation I Pokédex?',151,'Pokémon','Pokémon'],['What is Pikachu’s National Pokédex number?',25,'number','Pokémon'],['How many members begin the Fellowship of the Ring?',9,'members','Lord of the Rings'],['How many rings were given to the dwarf-lords?',7,'rings','Lord of the Rings'],['How many seasons does the HBO Game of Thrones series have?',8,'seasons','Game of Thrones'],['How many dragons hatch for Daenerys at the end of season one?',3,'dragons','Game of Thrones'],['How many dwarfs are in Disney’s Snow White?',7,'dwarfs','Disney'],['In which year was Disney’s The Lion King first released?',1994,'year','Disney'],['How many hearts does an octopus have?',3,'hearts','Marine Biology'],['How many pairs of gill slits do most sharks have?',5,'pairs','Marine Biology'],['How many neck vertebrae does a typical domestic cat have?',7,'vertebrae','Cats'],['How many toes does a typical cat have across all four paws?',18,'toes','Cats'],['How many legs does a spider have?',8,'legs','Animals'],['How many chambers does a crocodile’s heart have?',4,'chambers','Animals'],['In which year was the first Toy Story film released?',1995,'year','Films'],['In which year was the original Jurassic Park released?',1993,'year','Films'],['How many seasons does the original Friends series have?',10,'seasons','TV Shows'],['How many seasons does Breaking Bad have?',5,'seasons','TV Shows'],['How many Infinity Stones are there in the MCU?',6,'stones','Marvel'],['In which year was the first MCU Iron Man film released?',2008,'year','Marvel'],['In which year did Batman first appear in Detective Comics #27?',1939,'year','DC'],['In which year did Superman first appear in Action Comics #1?',1938,'year','DC'],['In which year was the first Sonic the Hedgehog game released?',1991,'year','Video Games'],['How many squares are in a standard Tetris tetromino?',4,'squares','Video Games'],['How many minutes are in a day?',1440,'minutes','General Knowledge'],['How many squares are on a chessboard?',64,'squares','General Knowledge']
].map((r,i)=>({id:`n${i}`,prompt:r[0],value:r[1],unit:r[2],category:r[3]}));
const quotes=[['May the Force be with you.','Star Wars','Films'],['I’ll be back.','The Terminator','Films'],['You shall not pass!','Gandalf','Lord of the Rings'],['My precious.','Gollum','Lord of the Rings'],['Winter is coming.','House Stark','Game of Thrones'],['A Lannister always pays his debts.','House Lannister','Game of Thrones'],['To infinity and beyond!','Buzz Lightyear','Disney'],['Just keep swimming.','Dory','Disney'],['It’s-a me, Mario!','Mario','Video Games'],['The cake is a lie.','Portal','Video Games'],['Yer a wizard, Harry.','Hagrid','Harry Potter'],['I am Iron Man.','Tony Stark','Marvel'],['I am Groot.','Groot','Marvel'],['Why so serious?','The Joker','DC'],['Gotta catch ’em all!','Pokémon','Pokémon'],['How you doin’?','Joey Tribbiani','TV Shows'],['Lovely jubbly!','Del Boy','TV Shows']].map((r,i)=>({id:`quote${i}`,category:r[2],prompt:`Who or what is associated with “${r[0]}”?`,answer:r[1]}));
const pictures=[
{prompt:'Which country’s flag is this?',answer:'Japan',options:['Japan','Bangladesh','South Korea','China'],svg:'<rect width="400" height="260" fill="white"/><circle cx="200" cy="130" r="75" fill="#bc002d"/>'},
{prompt:'Which country’s flag is this?',answer:'France',options:['France','Italy','Ireland','Romania'],svg:'<rect width="134" height="260" fill="#002395"/><rect x="134" width="133" height="260" fill="white"/><rect x="267" width="133" height="260" fill="#ed2939"/>'},
{prompt:'Which country’s flag is this?',answer:'Italy',options:['Italy','France','Ireland','Mexico'],svg:'<rect width="134" height="260" fill="#009246"/><rect x="134" width="133" height="260" fill="white"/><rect x="267" width="133" height="260" fill="#ce2b37"/>'},
{prompt:'Name this geometric shape.',answer:'Hexagon',options:['Hexagon','Pentagon','Octagon','Heptagon'],svg:'<rect width="400" height="260" fill="#182338"/><polygon points="110,130 155,52 245,52 290,130 245,208 155,208" fill="#f1be5b"/>'},
{prompt:'Name this geometric shape.',answer:'Pentagon',options:['Pentagon','Hexagon','Heptagon','Octagon'],svg:'<rect width="400" height="260" fill="#182338"/><polygon points="200,32 300,105 262,222 138,222 100,105" fill="#e96283"/>'},
{prompt:'Which country’s flag is this?',answer:'Ukraine',options:['Ukraine','Sweden','Finland','Greece'],svg:'<rect width="400" height="130" fill="#0057b7"/><rect y="130" width="400" height="130" fill="#ffd700"/>'}
].map((p,i)=>({...p,id:`pic${i}`,category:'General Knowledge',image:'data:image/svg+xml;base64,'+(typeof Buffer!=='undefined'?Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 260">${p.svg}</svg>`).toString('base64'):btoa(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 260">${p.svg}</svg>`))}));
const data={categories,questions,numeric,quotes,pictures}; if(typeof module!=='undefined')module.exports=data;else root.QuizData=data;
})(typeof globalThis!=='undefined'?globalThis:this);
